stop_words = set(["i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you", "your", "yours",
    "yourself", "yourselves", "he", "him", "his", "himself", "she", "her", "hers", "herself",
    "it", "its", "itself", "they", "them", "theirs", "themselves", "what", "which", "who",
    "whom", "this", "that", "these", "those", "am", "is", "are", "was", "were", "be", "been",
    "being", "have", "has", "had", "having", "do", "does", "did", "doing", "a", "an", "the", "and",
    "but", "if", "or", "because", "as", "until", "while", "of", "at", "by", "for", "with",
    "about", "against", "between", "into", "through", "during", "before", "after", "above",
    "below", "to", "from", "up", "down", "in", "out", "on", "off", "over", "under", "again",
    "further", "then", "once", "here", "there", "all", "any", "both", "each", "few", "more",
    "most", "some", "such", "no", "nor", "not", "only", "own", "same", "so", "than", "too",
    "very", "s", "t", "can", "will", "just", "don", "should", "shouldn", "would", "wouldn",
    "may", "might", "must", "need", "shall", "mustn", "ve", "y", "because", "out", "over",
    "even", "now", "up", "this", "down", "should", "under", "why", "back", "across", "through",
    "way", "forward", "more", "once", "indeed", "still", "its", "would", "the", "these",
    "will", "again", "never", "then", "that", "some", "through", "an", "any", "shall", "or",
    "first", "each", "aren", "might", "a", "and", "in", "for", "are", "have", "has", "with",
    "from", "by", "be", "as", "you", "do", "at", "this", "but", "his", "by", "on", "they",
    "which", "were", "here", "all", "there", "would", "their", "we", "he", "said", "was", "of",
    "to", "it", "and", "a", "in", "that", "have", "I", "for", "it", "not", "on", "with", "if",
    "as", "you", "be", "me", "of", "this", "is", "and", "the", "have", "from", "or", "at", "a",
    "my", "by", "one", "has", "with", "he", "are", "we", "what", "all", "were", "will", "to", "they",
    "there", "their", "any", "these", "can", "who", "give", "him", "again", "our", "then", "under",
    "one", "another", "through", "just", "form", "some", "an", "great", "think", "so", "because",
    "them", "make", "going", "when", "come", "could", "them", "seen", "other", "which", "does",
    "work", "get", "put", "say", "us", "our", "out", "if", "all"])